import { useState } from "react";
import { Link } from "wouter";
import { RoleProtectedRoute } from "@/components/auth/role-protected-route";
import { canManageSalary } from "@/lib/permissions";
import { useSalaryHistory, useSalaryApprovalActions } from "@/hooks/useData";
import { ReportPageShell } from "@/components/reports/report-page-shell";
import { ReportDataTable } from "@/components/reports/report-data-table";
import { formatLkr } from "@/lib/reportDatePresets";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/hooks/use-toast";
import { ArrowLeft } from "lucide-react";

const PAYMENT_METHODS = ["Cash", "Bank Transfer", "Cheque", "Other"];

function SalaryApprovalContent() {
  const { toast } = useToast();
  const [statusFilter, setStatusFilter] = useState("Generated");
  const { data: rows = [], isLoading, error } = useSalaryHistory({ status: statusFilter || undefined });
  const actions = useSalaryApprovalActions();
  const [payDialog, setPayDialog] = useState<any>(null);
  const [paymentMethod, setPaymentMethod] = useState("Bank Transfer");
  const [paymentReference, setPaymentReference] = useState("");
  const [rejectId, setRejectId] = useState<string | null>(null);
  const [rejectReason, setRejectReason] = useState("");

  const run = (fn: () => void) => {
    fn();
    toast({ title: "Updated" });
  };

  return (
    <ReportPageShell
      title="Salary Approval"
      loading={isLoading}
      error={error as Error | null}
      filters={
        <div className="flex gap-3 items-center">
          <Link href="/salary"><Button variant="ghost" size="sm"><ArrowLeft className="h-4 w-4 mr-1" />Back</Button></Link>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-40"><SelectValue /></SelectTrigger>
            <SelectContent>
              {["Generated", "Approved", "Paid", "Cancelled"].map((s) => (
                <SelectItem key={s} value={s}>{s}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      }
    >
      <ReportDataTable
        columns={[
          { key: "staffName", label: "Staff" },
          { key: "salaryMonth", label: "Month", render: (r) => String(r.salaryMonth).slice(0, 7) },
          { key: "finalSalary", label: "Final", render: (r) => formatLkr(Number(r.finalSalary)) },
          { key: "generatedByName", label: "Generated By" },
          { key: "createdAt", label: "Generated", render: (r) => r.createdAt ? new Date(String(r.createdAt)).toLocaleDateString() : "—" },
          { key: "status", label: "Status" },
          {
            key: "actions",
            label: "Actions",
            render: (r) => {
              const id = String(r.id);
              const status = String(r.status);
              return (
              <div className="flex flex-wrap gap-1">
                {status === "Generated" && (
                  <Button size="sm" variant="outline" onClick={() => run(() => actions.approve.mutate(id))}>Approve</Button>
                )}
                {status === "Approved" && (
                  <>
                    <Button size="sm" onClick={() => setPayDialog(r)}>Mark Paid</Button>
                    <Button size="sm" variant="outline" onClick={() => actions.returnForReview.mutate({ id })}>Return</Button>
                  </>
                )}
                {(status === "Generated" || status === "Approved") && (
                  <Button size="sm" variant="destructive" onClick={() => setRejectId(id)}>Reject</Button>
                )}
              </div>
            );},
          },
        ]}
        rows={rows}
        searchKeys={["staffName"]}
      />

      <Dialog open={!!payDialog} onOpenChange={() => setPayDialog(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Mark Salary Paid</DialogTitle></DialogHeader>
          <div className="space-y-3">
            <p className="text-sm">{payDialog?.staffName} — {formatLkr(Number(payDialog?.finalSalary))}</p>
            <div>
              <Label>Payment Method</Label>
              <Select value={paymentMethod} onValueChange={setPaymentMethod}>
                <SelectTrigger><SelectValue /></SelectTrigger>
                <SelectContent>
                  {PAYMENT_METHODS.map((m) => <SelectItem key={m} value={m}>{m}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label>Reference</Label>
              <Input value={paymentReference} onChange={(e) => setPaymentReference(e.target.value)} />
            </div>
          </div>
          <DialogFooter>
            <Button onClick={() => {
              if (!payDialog) return;
              actions.markPaid.mutate({ id: payDialog.id, paymentMethod, paymentReference });
              setPayDialog(null);
              toast({ title: "Marked as paid" });
            }}>Confirm Payment</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <Dialog open={!!rejectId} onOpenChange={() => setRejectId(null)}>
        <DialogContent>
          <DialogHeader><DialogTitle>Reject Salary</DialogTitle></DialogHeader>
          <Input placeholder="Reason" value={rejectReason} onChange={(e) => setRejectReason(e.target.value)} />
          <DialogFooter>
            <Button variant="destructive" onClick={() => {
              if (!rejectId || !rejectReason) return;
              actions.reject.mutate({ id: rejectId, reason: rejectReason });
              setRejectId(null);
              setRejectReason("");
            }}>Reject</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </ReportPageShell>
  );
}

export default function SalaryApprovalPage() {
  return (
    <RoleProtectedRoute allowed={canManageSalary}>
      <SalaryApprovalContent />
    </RoleProtectedRoute>
  );
}
