import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { RoleProtectedRoute } from "@/components/auth/role-protected-route";
import { canViewReports } from "@/lib/permissions";
import { useAttendanceReport } from "@/hooks/useData";
import { useAuth } from "@/context/auth-context";
import { useBranding } from "@/context/branding-context";
import { ReportPageShell, ReportSummaryCard } from "@/components/reports/report-page-shell";
import { ReportDateFilters } from "@/components/reports/report-date-filters";
import { ReportDataTable } from "@/components/reports/report-data-table";
import { StructuredReportActions } from "@/components/reports/structured-report-actions";
import { getDateRangeForPreset, type DatePreset } from "@/lib/reportDatePresets";

function AttendanceReportContent() {
  const { user } = useAuth();
  const { logoUri } = useBranding();
  const [preset, setPreset] = useState<DatePreset>("currentMonth");
  const [startDate, setStartDate] = useState(() => getDateRangeForPreset("currentMonth").startDate);
  const [endDate, setEndDate] = useState(() => getDateRangeForPreset("currentMonth").endDate);

  useEffect(() => {
    const r = getDateRangeForPreset(preset, startDate, endDate);
    setStartDate(r.startDate);
    setEndDate(r.endDate);
  }, [preset]);

  const { data, isLoading, error } = useAttendanceReport({ startDate, endDate }, !!startDate && !!endDate);
  const summary = data?.summary;

  const chartData = summary
    ? [{ name: "Attendance", present: summary.present, absent: summary.absent }]
    : [];

  return (
    <ReportPageShell
      title="Attendance Report"
      loading={isLoading}
      error={error as Error | null}
      filters={
        <ReportDateFilters preset={preset} onPresetChange={setPreset} startDate={startDate} endDate={endDate} onStartDateChange={setStartDate} onEndDateChange={setEndDate} />
      }
      actions={
        data ? (
          <StructuredReportActions
            reportTitle="Attendance Report"
            fileBaseName={`attendance-${startDate}`}
            columns={[
              { key: "date", label: "Date" },
              { key: "staffName", label: "Staff" },
              { key: "status", label: "Status" },
            ]}
            rows={(data.records ?? []).map((r: any) => ({ date: r.date, staffName: r.staffName, status: r.status }))}
            logoUri={logoUri}
            meta={[
              { label: "Attendance %", value: `${data.attendancePercent}%` },
              { label: "Generated By", value: user?.name ?? "" },
            ]}
          />
        ) : null
      }
    >
      {data && summary && (
        <>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4 mb-6">
            <ReportSummaryCard label="Present" value={String(summary.present)} />
            <ReportSummaryCard label="Absent" value={String(summary.absent)} />
            <ReportSummaryCard label="Attendance %" value={`${data.attendancePercent}%`} />
          </div>
          <div className="h-56 mb-6">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis dataKey="name" />
                <YAxis />
                <Tooltip />
                <Legend />
                <Bar dataKey="present" fill="#16A34A" name="Present" />
                <Bar dataKey="absent" fill="#DC2626" name="Absent" />
              </BarChart>
            </ResponsiveContainer>
          </div>
          <ReportDataTable
            columns={[
              { key: "date", label: "Date" },
              { key: "staffName", label: "Staff" },
              { key: "status", label: "Status" },
              { key: "editReason", label: "Edit Reason", render: (r) => String((r as any).editReason ?? "—") },
            ]}
            rows={data.records ?? []}
            searchKeys={["staffName", "status", "date"]}
          />
        </>
      )}
    </ReportPageShell>
  );
}

export default function AttendanceReportPage() {
  return (
    <RoleProtectedRoute allowed={canViewReports}>
      <AttendanceReportContent />
    </RoleProtectedRoute>
  );
}
