import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { RoleProtectedRoute } from "@/components/auth/role-protected-route";
import { canViewManagementReports, isManagementRole } from "@/lib/permissions";
import { useExpenseReport, useDeleteExpense } from "@/hooks/useData";
import { useAuth } from "@/context/auth-context";
import { useBranding } from "@/context/branding-context";
import { ReportPageShell, ReportSummaryCard } from "@/components/reports/report-page-shell";
import { ReportDateFilters } from "@/components/reports/report-date-filters";
import { ReportDataTable } from "@/components/reports/report-data-table";
import { StructuredReportActions } from "@/components/reports/structured-report-actions";
import { getDateRangeForPreset, formatLkr, type DatePreset } from "@/lib/reportDatePresets";

function ExpenseReportContent() {
  const { user } = useAuth();
  const [, setLocation] = useLocation();
  const { logoUri } = useBranding();
  const deleteExpense = useDeleteExpense();
  const canManage = isManagementRole(user?.role);
  const [preset, setPreset] = useState<DatePreset>("currentMonth");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");

  useEffect(() => {
    const r = getDateRangeForPreset(preset, startDate, endDate);
    setStartDate(r.startDate);
    setEndDate(r.endDate);
  }, [preset]);

  const { data, isLoading, error } = useExpenseReport({ startDate, endDate }, !!startDate && !!endDate);
  const categories = data?.byCategory ?? {};

  return (
    <ReportPageShell
      title="Expense Report"
      loading={isLoading}
      error={error as Error | null}
      filters={
        <ReportDateFilters preset={preset} onPresetChange={setPreset} startDate={startDate} endDate={endDate} onStartDateChange={setStartDate} onEndDateChange={setEndDate} />
      }
      actions={
        data ? (
          <StructuredReportActions
            reportTitle="Expense Report"
            fileBaseName={`expenses-${startDate}`}
            columns={[
              { key: "expenseDate", label: "Date" },
              { key: "category", label: "Category" },
              { key: "amount", label: "Amount" },
              { key: "createdByName", label: "Staff" },
            ]}
            rows={(data.items ?? []).map((e: any) => ({ ...e, amount: formatLkr(Number(e.amount)) }))}
            logoUri={logoUri}
            meta={[{ label: "Total", value: formatLkr(data.total) }, { label: "Generated By", value: user?.name ?? "" }]}
          />
        ) : null
      }
    >
      {data && (
        <>
          <ReportSummaryCard label="Total Expenses" value={formatLkr(data.total)} />
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4">
            {Object.entries(categories).map(([cat, amt]) => (
              <ReportSummaryCard key={cat} label={cat} value={formatLkr(Number(amt))} />
            ))}
          </div>
          <div className="mt-6">
            <ReportDataTable
              columns={[
                { key: "expenseDate", label: "Date" },
                { key: "category", label: "Category" },
                { key: "amount", label: "Amount", render: (r) => formatLkr(Number(r.amount)) },
                { key: "createdByName", label: "Staff" },
                { key: "description", label: "Remarks", render: (r) => String(r.description ?? r.remarks ?? "—") },
              ]}
              rows={data.items ?? []}
              rowActions={{
                canManage,
                onEdit: (row) => setLocation(`/expenses/edit/${row.id}`),
                onDelete: async (row) => {
                  if (!confirm("Delete this expense?")) return;
                  await deleteExpense.mutateAsync(String(row.id));
                },
              }}
            />
          </div>
        </>
      )}
    </ReportPageShell>
  );
}

export default function ExpenseReportPage() {
  return (
    <RoleProtectedRoute allowed={canViewManagementReports}>
      <ExpenseReportContent />
    </RoleProtectedRoute>
  );
}
