import { useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { RoleProtectedRoute } from "@/components/auth/role-protected-route";
import { canViewSalaryReports } from "@/lib/permissions";
import { useIncentiveReport } from "@/hooks/useData";
import { useAuth } from "@/context/auth-context";
import { useBranding } from "@/context/branding-context";
import { ReportPageShell } from "@/components/reports/report-page-shell";
import { ReportDateFilters } from "@/components/reports/report-date-filters";
import { ReportDataTable } from "@/components/reports/report-data-table";
import { StructuredReportActions } from "@/components/reports/structured-report-actions";
import { getDateRangeForPreset, formatLkr, type DatePreset } from "@/lib/reportDatePresets";

function IncentiveReportContent() {
  const { user } = useAuth();
  const { logoUri } = useBranding();
  const [preset, setPreset] = useState<DatePreset>("currentMonth");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");

  useEffect(() => {
    const r = getDateRangeForPreset(preset, startDate, endDate);
    setStartDate(r.startDate);
    setEndDate(r.endDate);
  }, [preset]);

  const { data, isLoading, error } = useIncentiveReport({ startDate, endDate }, !!startDate && !!endDate);
  const rows = data?.rows ?? [];

  return (
    <ReportPageShell
      title="Incentive Report"
      description="Daily incentive formula: Colombo clinic visits + floor(IP sessions ÷ 2)."
      loading={isLoading}
      error={error as Error | null}
      filters={
        <ReportDateFilters preset={preset} onPresetChange={setPreset} startDate={startDate} endDate={endDate} onStartDateChange={setStartDate} onEndDateChange={setEndDate} />
      }
      actions={
        rows.length > 0 ? (
          <StructuredReportActions
            reportTitle="Incentive Report"
            fileBaseName={`incentive-${startDate}`}
            columns={[
              { key: "staffName", label: "Staff" },
              { key: "clinicVisits", label: "Clinic Visits" },
              { key: "sessions", label: "Sessions" },
              { key: "incentiveCount", label: "Count" },
              { key: "incentiveAmount", label: "Amount" },
            ]}
            rows={rows.map((r: any) => ({ ...r, incentiveAmount: formatLkr(r.incentiveAmount) }))}
            logoUri={logoUri}
            meta={[{ label: "Generated By", value: user?.name ?? "" }]}
          />
        ) : null
      }
    >
      {rows.length > 0 && (
        <>
          <div className="h-64 mb-6">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={rows.slice(0, 10)} layout="vertical" margin={{ left: 80 }}>
                <CartesianGrid strokeDasharray="3 3" />
                <XAxis type="number" />
                <YAxis type="category" dataKey="staffName" width={80} tick={{ fontSize: 11 }} />
                <Tooltip />
                <Bar dataKey="incentiveCount" fill="#1873A8" name="Incentive Count" />
              </BarChart>
            </ResponsiveContainer>
          </div>
          <ReportDataTable
            columns={[
              { key: "staffName", label: "Staff" },
              { key: "clinicVisits", label: "Clinic Visits" },
              { key: "sessions", label: "Sessions" },
              { key: "incentiveCount", label: "Incentive Count" },
              { key: "incentiveAmount", label: "Amount", render: (r) => formatLkr(Number(r.incentiveAmount)) },
            ]}
            rows={rows}
            searchKeys={["staffName"]}
          />
        </>
      )}
    </ReportPageShell>
  );
}

export default function IncentiveReportPage() {
  return (
    <RoleProtectedRoute allowed={canViewSalaryReports}>
      <IncentiveReportContent />
    </RoleProtectedRoute>
  );
}
