import { useEffect, useState } from "react";
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis, CartesianGrid } from "recharts";
import { RoleProtectedRoute } from "@/components/auth/role-protected-route";
import { canViewManagementReports } from "@/lib/permissions";
import { useRevenueReport } from "@/hooks/useData";
import { useBranding } from "@/context/branding-context";
import { useAuth } from "@/context/auth-context";
import { ReportPageShell, ReportSummaryCard } from "@/components/reports/report-page-shell";
import { ReportDateFilters } from "@/components/reports/report-date-filters";
import { StructuredReportActions } from "@/components/reports/structured-report-actions";
import { getDateRangeForPreset, formatLkr, type DatePreset } from "@/lib/reportDatePresets";
import { format } from "date-fns";

function RevenueReportContent() {
  const { user } = useAuth();
  const { logoUri } = useBranding();
  const [preset, setPreset] = useState<DatePreset>("currentMonth");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");

  useEffect(() => {
    const r = getDateRangeForPreset(preset, startDate, endDate);
    setStartDate(r.startDate);
    setEndDate(r.endDate);
  }, [preset]);

  const { data, isLoading, error } = useRevenueReport({ startDate, endDate }, !!startDate && !!endDate);

  const exportRows =
    data?.dailyTrend?.map((d: any) => ({
      date: d.date,
      revenue: formatLkr(d.revenue),
    })) ?? [];

  return (
    <ReportPageShell
      title="Revenue Report"
      description="Paid clinic, home, and session revenue from the calculation engine."
      loading={isLoading}
      error={error as Error | null}
      filters={
        <ReportDateFilters
          preset={preset}
          onPresetChange={setPreset}
          startDate={startDate}
          endDate={endDate}
          onStartDateChange={setStartDate}
          onEndDateChange={setEndDate}
        />
      }
      actions={
        data ? (
          <StructuredReportActions
            reportTitle="Revenue Report"
            fileBaseName={`revenue-${startDate}-${endDate}`}
            columns={[
              { key: "date", label: "Date" },
              { key: "revenue", label: "Revenue" },
            ]}
            rows={exportRows}
            logoUri={logoUri}
            meta={[
              { label: "Period", value: `${startDate} to ${endDate}` },
              { label: "Total", value: formatLkr(data.totalRevenue) },
              { label: "Generated By", value: user?.name ?? "" },
            ]}
          />
        ) : null
      }
    >
      {data && (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <ReportSummaryCard label="Total Revenue" value={formatLkr(data.totalRevenue)} />
            <ReportSummaryCard label="Paid Revenue" value={formatLkr(data.paidRevenue)} />
            <ReportSummaryCard label="Unpaid (Range)" value={formatLkr(data.unpaidRevenue)} />
            <ReportSummaryCard label="Outstanding" value={formatLkr(data.outstandingBalance)} sub="All unpaid visits" />
          </div>
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4 mt-4">
            <ReportSummaryCard label="Clinic Revenue" value={formatLkr(data.breakdown?.clinic ?? 0)} />
            <ReportSummaryCard label="Home Visit Revenue" value={formatLkr(data.breakdown?.home ?? 0)} />
          </div>
          {data.dailyTrend?.length > 0 && (
            <div className="mt-6 h-64">
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={data.dailyTrend}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="date" tick={{ fontSize: 10 }} />
                  <YAxis tick={{ fontSize: 10 }} />
                  <Tooltip formatter={(v: number) => formatLkr(v)} />
                  <Line type="monotone" dataKey="revenue" stroke="hsl(var(--primary))" strokeWidth={2} dot={{ r: 2 }} />
                </LineChart>
              </ResponsiveContainer>
            </div>
          )}
          <p className="text-xs text-muted-foreground mt-4">Generated {format(new Date(), "dd MMM yyyy HH:mm")}</p>
        </>
      )}
    </ReportPageShell>
  );
}

export default function RevenueReportPage() {
  return (
    <RoleProtectedRoute allowed={canViewManagementReports}>
      <RevenueReportContent />
    </RoleProtectedRoute>
  );
}
