import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { RoleProtectedRoute } from "@/components/auth/role-protected-route";
import { canViewReports } from "@/lib/permissions";
import { useSessionReport } from "@/hooks/useData";
import { useAuth } from "@/context/auth-context";
import { useBranding } from "@/context/branding-context";
import { ReportPageShell, ReportSummaryCard } from "@/components/reports/report-page-shell";
import { ReportDateFilters } from "@/components/reports/report-date-filters";
import { ReportDataTable } from "@/components/reports/report-data-table";
import { StructuredReportActions } from "@/components/reports/structured-report-actions";
import { getDateRangeForPreset, type DatePreset } from "@/lib/reportDatePresets";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useStaff } from "@/hooks/useData";
import { isManagementRole } from "@/lib/permissions";

function SessionReportContent() {
  const { user } = useAuth();
  const [, setLocation] = useLocation();
  const { logoUri } = useBranding();
  const isMgmt = isManagementRole(user?.role);
  const [preset, setPreset] = useState<DatePreset>("currentMonth");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");
  const [staffId, setStaffId] = useState("");
  const [typeFilter, setTypeFilter] = useState("");

  useEffect(() => {
    const r = getDateRangeForPreset(preset, startDate, endDate);
    setStartDate(r.startDate);
    setEndDate(r.endDate);
  }, [preset]);

  const { data, isLoading, error } = useSessionReport(
    { startDate, endDate, staffId: isMgmt ? staffId || undefined : user?.id },
    !!startDate && !!endDate
  );
  const { data: staffList } = useStaff({ includeInactive: false });

  const rows = (data?.rows ?? []).filter((r: any) => !typeFilter || r.type === typeFilter);

  return (
    <ReportPageShell
      title="Session Report"
      description="Outpatient visits and in-patient sessions — daily, weekly, monthly, or custom range."
      loading={isLoading}
      error={error as Error | null}
      filters={
        <div className="space-y-3">
          <ReportDateFilters
            preset={preset}
            onPresetChange={setPreset}
            startDate={startDate}
            endDate={endDate}
            onStartDateChange={setStartDate}
            onEndDateChange={setEndDate}
          />
          <div className="flex flex-wrap gap-3">
            <Select value={typeFilter || "all"} onValueChange={(v) => setTypeFilter(v === "all" ? "" : v)}>
              <SelectTrigger className="w-40"><SelectValue placeholder="All types" /></SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All types</SelectItem>
                <SelectItem value="Outpatient">Outpatient</SelectItem>
                <SelectItem value="In-Patient">In-Patient</SelectItem>
              </SelectContent>
            </Select>
            {isMgmt && (
              <Select value={staffId || "all"} onValueChange={(v) => setStaffId(v === "all" ? "" : v)}>
                <SelectTrigger className="w-48"><SelectValue placeholder="All therapists" /></SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All therapists</SelectItem>
                  {(staffList ?? []).map((s: any) => (
                    <SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            )}
          </div>
        </div>
      }
      actions={
        data ? (
          <StructuredReportActions
            reportTitle="Session Report"
            fileBaseName={`sessions-${startDate}`}
            columns={[
              { key: "type", label: "Type" },
              { key: "date", label: "Date" },
              { key: "sessionNumber", label: "Session #" },
              { key: "staffName", label: "Therapist" },
              { key: "patientOrAdmission", label: "Patient" },
              { key: "branch", label: "Branch" },
            ]}
            rows={rows}
            logoUri={logoUri}
            meta={[
              { label: "Period", value: `${startDate} → ${endDate}` },
              { label: "Total Sessions", value: String(data.summary?.total ?? 0) },
              { label: "Generated By", value: user?.name ?? "" },
            ]}
          />
        ) : null
      }
    >
      {data && (
        <>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
            <ReportSummaryCard label="Total Sessions" value={String(data.summary?.total ?? 0)} />
            <ReportSummaryCard label="Outpatient" value={String(data.summary?.totalOutpatient ?? 0)} />
            <ReportSummaryCard label="In-Patient" value={String(data.summary?.totalInpatient ?? 0)} />
            <ReportSummaryCard label="Therapists" value={String(data.summary?.byTherapist?.length ?? 0)} />
          </div>
          <ReportDataTable
            columns={[
              { key: "type", label: "Type" },
              { key: "date", label: "Date" },
              { key: "sessionNumber", label: "Session #", render: (r) => String(r.sessionNumber) },
              { key: "staffName", label: "Therapist" },
              { key: "patientOrAdmission", label: "Patient" },
              { key: "branch", label: "Branch", render: (r) => String(r.branch ?? "—") },
              { key: "treatment", label: "Treatment", render: (r) => String(r.treatment ?? "").slice(0, 60) },
            ]}
            rows={rows}
            rowActions={{
              canManage: isMgmt,
              onEdit: (row) => {
                if (row.type === "In-Patient" && row.admissionId) {
                  setLocation(`/inpatients/${row.admissionId}`);
                } else if (row.visitId) {
                  setLocation(`/visits/edit/${row.visitId}`);
                }
              },
            }}
          />
        </>
      )}
    </ReportPageShell>
  );
}

export default function SessionReportPage() {
  return (
    <RoleProtectedRoute allowed={canViewReports}>
      <SessionReportContent />
    </RoleProtectedRoute>
  );
}
