import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowLeft } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/context/auth-context";
import { useBranding } from "@/context/branding-context";
import { useStaffReport, useStaffMember } from "@/hooks/useData";
import { ReportPageShell, ReportSummaryCard } from "@/components/reports/report-page-shell";
import { ReportDateFilters } from "@/components/reports/report-date-filters";
import { ReportDataTable } from "@/components/reports/report-data-table";
import { StructuredReportActions } from "@/components/reports/structured-report-actions";
import { getDateRangeForPreset, formatLkr, type DatePreset } from "@/lib/reportDatePresets";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export default function StaffReportPage() {
  const [, params] = useRoute("/staff/:id/report");
  const staffId = params?.id ?? "";
  const { user } = useAuth();
  const { logoUri } = useBranding();
  const isMgmt = ["Admin", "MD"].includes(user?.role ?? "");

  if (!isMgmt && user?.id !== staffId) {
    return <div className="p-4 text-muted-foreground">Unauthorized</div>;
  }

  const { data: staffMember } = useStaffMember(staffId);
  const [preset, setPreset] = useState<DatePreset>("currentMonth");
  const [startDate, setStartDate] = useState("");
  const [endDate, setEndDate] = useState("");

  useEffect(() => {
    const r = getDateRangeForPreset(preset, startDate, endDate);
    setStartDate(r.startDate);
    setEndDate(r.endDate);
  }, [preset]);

  const { data, isLoading, error } = useStaffReport({ staffId, startDate, endDate }, !!staffId && !!startDate);
  const p = data?.payroll;

  return (
    <ReportPageShell
      title={`Staff Report — ${staffMember?.name ?? ""}`}
      loading={isLoading}
      error={error as Error | null}
      filters={
        <ReportDateFilters preset={preset} onPresetChange={setPreset} startDate={startDate} endDate={endDate} onStartDateChange={setStartDate} onEndDateChange={setEndDate} />
      }
      actions={
        p ? (
          <StructuredReportActions
            reportTitle={`Staff Report — ${staffMember?.name}`}
            fileBaseName={`staff-report-${staffId}`}
            columns={[
              { key: "label", label: "Item" },
              { key: "value", label: "Amount" },
            ]}
            rows={[
              { label: "Basic Salary", value: formatLkr(p.basicSalary) },
              { label: "Incentives", value: formatLkr(p.incentiveTotal) },
              { label: "Home Visits", value: formatLkr(p.homeIncome) },
              { label: "OT", value: formatLkr(p.otIncome) },
              { label: "Fines", value: formatLkr(p.finesTotal) },
              { label: "Final Salary", value: formatLkr(p.finalSalary) },
            ]}
            logoUri={logoUri}
            meta={[{ label: "Period", value: `${startDate} to ${endDate}` }, { label: "Generated By", value: user?.name ?? "" }]}
          />
        ) : null
      }
    >
      <Link href={`/staff/${staffId}`}>
        <Button variant="ghost" size="sm" className="mb-2">
          <ArrowLeft className="h-4 w-4 mr-1" /> Back to profile
        </Button>
      </Link>
      {p && data && (
        <>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <ReportSummaryCard label="Visits" value={String(data.visits.length)} />
            <ReportSummaryCard label="Sessions" value={String(data.sessions.length)} />
            <ReportSummaryCard label="Home Visits" value={String(data.homeVisits.length)} />
            <ReportSummaryCard label="Final Salary" value={formatLkr(p.finalSalary)} />
          </div>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mt-4">
            <ReportSummaryCard label="Incentive" value={formatLkr(p.incentiveTotal)} sub={`Count: ${p.incentiveCount}`} />
            <ReportSummaryCard label="Present Days" value={String(p.presentDays)} />
            <ReportSummaryCard label="Absent Days" value={String(p.absentDays)} />
            <ReportSummaryCard label="OT Hours" value={String(p.totalOt)} />
          </div>
          <Tabs defaultValue="visits" className="mt-6">
            <TabsList>
              <TabsTrigger value="visits">Visits</TabsTrigger>
              <TabsTrigger value="sessions">Sessions</TabsTrigger>
              <TabsTrigger value="fines">Fines</TabsTrigger>
              <TabsTrigger value="attendance">Attendance</TabsTrigger>
            </TabsList>
            <TabsContent value="visits">
              <ReportDataTable
                columns={[
                  { key: "visitDate", label: "Date" },
                  { key: "patientId", label: "Patient" },
                  { key: "branch", label: "Branch" },
                  { key: "paymentAmount", label: "Amount", render: (r) => formatLkr(Number(r.paymentAmount)) },
                  { key: "paymentStatus", label: "Status" },
                ]}
                rows={data.visits}
              />
            </TabsContent>
            <TabsContent value="sessions">
              <ReportDataTable
                columns={[
                  { key: "sessionDate", label: "Date" },
                  { key: "patientName", label: "Patient" },
                  { key: "sessionNumber", label: "Session #" },
                ]}
                rows={data.sessions}
              />
            </TabsContent>
            <TabsContent value="fines">
              <ReportDataTable
                columns={[
                  { key: "fineDate", label: "Date" },
                  { key: "reason", label: "Reason" },
                  { key: "amount", label: "Amount", render: (r) => formatLkr(Number(r.amount)) },
                  { key: "createdByName", label: "Created By" },
                ]}
                rows={data.fines}
              />
            </TabsContent>
            <TabsContent value="attendance">
              <ReportDataTable
                columns={[
                  { key: "date", label: "Date" },
                  { key: "status", label: "Status" },
                  { key: "editReason", label: "Edit Reason", render: (r) => String((r as any).editReason ?? "—") },
                ]}
                rows={data.attendance}
              />
            </TabsContent>
          </Tabs>
        </>
      )}
    </ReportPageShell>
  );
}
