import { useState } from "react";
import { Link, useLocation } from "wouter";
import { RoleProtectedRoute } from "@/components/auth/role-protected-route";
import { canViewReports, isManagementRole } from "@/lib/permissions";
import { useUnpaidReport, useDeleteVisit } from "@/hooks/useData";
import { useAuth } from "@/context/auth-context";
import { useBranding } from "@/context/branding-context";
import { ReportPageShell, ReportSummaryCard } from "@/components/reports/report-page-shell";
import { ReportDataTable } from "@/components/reports/report-data-table";
import { StructuredReportActions } from "@/components/reports/structured-report-actions";
import { CollectPaymentDialog } from "@/components/patients/collect-payment-dialog";
import { formatLkr } from "@/lib/reportDatePresets";
import { Button } from "@/components/ui/button";
import { Banknote } from "lucide-react";

function UnpaidVisitsContent() {
  const { user } = useAuth();
  const [, setLocation] = useLocation();
  const { logoUri } = useBranding();
  const { data, isLoading, error, refetch } = useUnpaidReport();
  const deleteVisit = useDeleteVisit();
  const [paymentVisit, setPaymentVisit] = useState<any>(null);
  const canCollect = ["Admin", "MD", "Receptionist"].includes(user?.role ?? "");
  const canManage = isManagementRole(user?.role);

  const rows = data?.rows ?? [];

  return (
    <ReportPageShell
      title="Unpaid Visits"
      description="Outstanding visits remain until payment status is Paid — not filtered by month."
      loading={isLoading}
      error={error as Error | null}
      actions={
        data ? (
          <StructuredReportActions
            reportTitle="Unpaid Visits"
            fileBaseName="unpaid-visits"
            columns={[
              { key: "patientName", label: "Patient" },
              { key: "visitDate", label: "Date" },
              { key: "amount", label: "Amount" },
              { key: "outstandingBalance", label: "Outstanding" },
              { key: "branch", label: "Branch" },
              { key: "therapistName", label: "Therapist" },
              { key: "paymentStatus", label: "Status" },
            ]}
            rows={rows.map((r: any) => ({
              ...r,
              amount: formatLkr(r.amount),
              outstandingBalance: formatLkr(r.outstandingBalance ?? r.amount),
            }))}
            logoUri={logoUri}
            meta={[
              { label: "Total Outstanding", value: formatLkr(data.totalAmount) },
              { label: "Patients", value: String(data.patientCount) },
              { label: "Generated By", value: user?.name ?? "" },
            ]}
          />
        ) : null
      }
    >
      {data && (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-6">
            <ReportSummaryCard label="Outstanding Amount" value={formatLkr(data.totalAmount)} />
            <ReportSummaryCard label="Unpaid Patients" value={String(data.patientCount)} />
          </div>
          <ReportDataTable
            columns={[
              {
                key: "patientName",
                label: "Patient",
                render: (r) => (
                  <Link href={`/patients/${r.patientId}`} className="text-primary hover:underline">
                    {String(r.patientName)}
                  </Link>
                ),
              },
              { key: "visitDate", label: "Visit Date" },
              { key: "amount", label: "Amount", render: (r) => formatLkr(Number(r.amount)) },
              { key: "outstandingBalance", label: "Outstanding", render: (r) => formatLkr(Number(r.outstandingBalance ?? r.amount)) },
              { key: "branch", label: "Branch" },
              { key: "therapistName", label: "Therapist" },
              { key: "paymentStatus", label: "Status" },
              ...(canCollect ? [{
                key: "actions",
                label: "",
                render: (r: any) => (
                  <Button size="sm" variant="outline" onClick={() => setPaymentVisit({
                    id: r.visitId,
                    paymentAmount: r.amount,
                    amountPaid: Number(r.amount) - Number(r.outstandingBalance ?? r.amount),
                    paymentStatus: r.paymentStatus,
                    patientName: r.patientName,
                  })}>
                    <Banknote className="h-3 w-3 mr-1" /> Collect
                  </Button>
                ),
              }] : []),
            ]}
            rows={rows}
            rowActions={{
              canManage,
              onEdit: (row) => setLocation(`/visits/edit/${row.visitId}`),
              onDelete: async (row) => {
                if (!confirm("Delete this visit record?")) return;
                await deleteVisit.mutateAsync(String(row.visitId));
                refetch();
              },
            }}
          />
          <CollectPaymentDialog
            visit={paymentVisit}
            open={!!paymentVisit}
            onOpenChange={(open) => !open && setPaymentVisit(null)}
            onSuccess={() => refetch()}
          />
        </>
      )}
    </ReportPageShell>
  );
}

export default function UnpaidVisitsPage() {
  return (
    <RoleProtectedRoute allowed={canViewReports}>
      <UnpaidVisitsContent />
    </RoleProtectedRoute>
  );
}
