import { Link } from "wouter";
import { useRef, useState } from "react";
import { RoleProtectedRoute } from "@/components/auth/role-protected-route";
import { canExportPatients } from "@/lib/permissions";
import { usePatientExport } from "@/hooks/useData";
import { useAuth } from "@/context/auth-context";
import { useBranding } from "@/context/branding-context";
import { ReportPageShell } from "@/components/reports/report-page-shell";
import { ReportDataTable } from "@/components/reports/report-data-table";
import { StructuredReportActions } from "@/components/reports/structured-report-actions";
import { formatLkr } from "@/lib/reportDatePresets";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { useToast } from "@/hooks/use-toast";
import { downloadPatientIdCard } from "@/lib/idCard";
import { ArrowLeft, Download, Loader2, Square } from "lucide-react";

function PatientExportContent() {
  const { user } = useAuth();
  const { logoUri } = useBranding();
  const { data: rows = [], isLoading, error } = usePatientExport();
  const { toast } = useToast();
  const [bulkDownloading, setBulkDownloading] = useState(false);
  const [bulkProgress, setBulkProgress] = useState({ current: 0, total: 0 });
  const cancelRef = useRef(false);

  const handleBulkDownload = async () => {
    if (!rows.length || bulkDownloading) return;
    cancelRef.current = false;
    setBulkDownloading(true);
    setBulkProgress({ current: 0, total: rows.length });
    for (let i = 0; i < rows.length; i += 1) {
      if (cancelRef.current) break;
      const row = rows[i] as any;
      try {
        await downloadPatientIdCard({
          kind: "outpatient",
          recordId: row.patientId,
          patientCode: row.patientCode ?? row.patientId,
          qrToken: null,
        });
      } catch (err) {
        toast({
          title: "Could not download ID card",
          description: err instanceof Error ? err.message : "Unknown error",
          variant: "destructive",
        });
      } finally {
        setBulkProgress((prev) => ({ ...prev, current: i + 1 }));
      }
    }
    setBulkDownloading(false);
  };

  const handleCancelBulkDownload = () => {
    cancelRef.current = true;
    setBulkDownloading(false);
  };

  const exportRows = rows.map((r: any) => ({
    patientCode: r.patientCode || r.patientId,
    patientName: r.patientName,
    phone: r.phone,
    branch: r.branch,
    therapist: r.therapist,
    visits: String(r.visits),
    sessions: String(r.sessions),
    outstandingAmount: formatLkr(r.outstandingAmount),
    status: r.status,
  }));

  const bulkPercent =
    bulkProgress.total > 0 ? Math.round((bulkProgress.current / bulkProgress.total) * 100) : 0;

  return (
    <ReportPageShell
      title="Patient Export"
      description="All patients with visits, sessions, and outstanding balances."
      loading={isLoading}
      error={error as Error | null}
      filters={
        <Link href="/patients">
          <Button variant="ghost" size="sm"><ArrowLeft className="h-4 w-4 mr-1" />Back to Patients</Button>
        </Link>
      }
      actions={
        rows.length > 0 ? (
          <div className="flex flex-wrap items-center gap-2">
            <StructuredReportActions
              reportTitle="Patient Register"
              fileBaseName="patients-export"
              columns={[
                { key: "patientCode", label: "Patient ID" },
                { key: "patientName", label: "Name" },
                { key: "phone", label: "Phone" },
                { key: "branch", label: "Branch" },
                { key: "therapist", label: "Therapist" },
                { key: "visits", label: "Visits" },
                { key: "sessions", label: "Sessions" },
                { key: "outstandingAmount", label: "Outstanding" },
                { key: "status", label: "Status" },
              ]}
              rows={exportRows}
              logoUri={logoUri}
              meta={[
                { label: "Total Patients", value: String(rows.length) },
                { label: "Generated By", value: user?.name ?? "" },
                { label: "Generated", value: new Date().toLocaleString() },
              ]}
            />
            <Button
              variant="outline"
              onClick={handleBulkDownload}
              disabled={bulkDownloading}
            >
              {bulkDownloading ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Download className="h-4 w-4 mr-2" />
              )}
              Download ID Cards
            </Button>
            {bulkDownloading && (
              <Button variant="ghost" onClick={handleCancelBulkDownload}>
                <Square className="h-4 w-4 mr-2" />
                Cancel
              </Button>
            )}
          </div>
        ) : null
      }
    >
      {bulkDownloading && (
        <div className="rounded-lg border bg-card p-3">
          <div className="flex items-center justify-between text-sm font-medium text-foreground">
            <span>Downloading ID cards...</span>
            <span>
              {bulkProgress.current}/{bulkProgress.total}
            </span>
          </div>
          <Progress className="mt-2" value={bulkPercent} />
          <div className="mt-2 text-xs text-muted-foreground">
            Keep this tab open while downloads continue.
          </div>
        </div>
      )}
      <ReportDataTable
        columns={[
          { key: "patientCode", label: "ID", render: (r) => String(r.patientCode || r.patientId) },
          { key: "patientName", label: "Name" },
          { key: "phone", label: "Phone" },
          { key: "branch", label: "Branch" },
          { key: "therapist", label: "Therapist" },
          { key: "visits", label: "Visits" },
          { key: "sessions", label: "Sessions" },
          { key: "outstandingAmount", label: "Outstanding", render: (r) => formatLkr(Number(r.outstandingAmount)) },
          { key: "status", label: "Status" },
        ]}
        rows={rows}
        searchKeys={["patientName", "phone", "patientCode", "therapist"]}
      />
    </ReportPageShell>
  );
}

export default function PatientExportPage() {
  return (
    <RoleProtectedRoute allowed={canExportPatients}>
      <PatientExportContent />
    </RoleProtectedRoute>
  );
}
