import { Link } from "wouter";
import { useState } from "react";
import { RoleProtectedRoute } from "@/components/auth/role-protected-route";
import { canExportPatients } from "@/lib/permissions";
import { usePatientExport } from "@/hooks/useData";
import { useAuth } from "@/context/auth-context";
import { useBranding } from "@/context/branding-context";
import { ReportPageShell } from "@/components/reports/report-page-shell";
import { ReportDataTable } from "@/components/reports/report-data-table";
import { StructuredReportActions } from "@/components/reports/structured-report-actions";
import { formatLkr } from "@/lib/reportDatePresets";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { useToast } from "@/hooks/use-toast";
import { downloadPatientIdCardsZip } from "@/lib/idCard";
import { ArrowLeft, Download, Loader2 } from "lucide-react";

function PatientExportContent() {
  const { user } = useAuth();
  const { logoUri } = useBranding();
  const { data: rows = [], isLoading, error } = usePatientExport();
  const { toast } = useToast();
  const [bulkDownloading, setBulkDownloading] = useState(false);
  const [bulkTotal, setBulkTotal] = useState(0);

  const handleBulkDownload = async () => {
    if (!rows.length || bulkDownloading) return;
    setBulkDownloading(true);
    setBulkTotal(rows.length);
    try {
      const patientIds = rows.map((row: any) => String(row.patientId));
      await downloadPatientIdCardsZip(patientIds);
      toast({ title: `Downloaded ${patientIds.length} ID cards as ZIP` });
    } catch (err) {
      toast({
        title: "Could not download ID cards",
        description: err instanceof Error ? err.message : "Unknown error",
        variant: "destructive",
      });
    } finally {
      setBulkDownloading(false);
    }
  };

  const exportRows = rows.map((r: any) => ({
    patientCode: r.patientCode || r.patientId,
    patientName: r.patientName,
    phone: r.phone,
    branch: r.branch,
    therapist: r.therapist,
    visits: String(r.visits),
    sessions: String(r.sessions),
    outstandingAmount: formatLkr(r.outstandingAmount),
    status: r.status,
  }));

  return (
    <ReportPageShell
      title="Patient Export"
      description="All patients with visits, sessions, and outstanding balances."
      loading={isLoading}
      error={error as Error | null}
      filters={
        <Link href="/patients">
          <Button variant="ghost" size="sm"><ArrowLeft className="h-4 w-4 mr-1" />Back to Patients</Button>
        </Link>
      }
      actions={
        rows.length > 0 ? (
          <div className="flex flex-wrap items-center gap-2">
            <StructuredReportActions
              reportTitle="Patient Register"
              fileBaseName="patients-export"
              columns={[
                { key: "patientCode", label: "Patient ID" },
                { key: "patientName", label: "Name" },
                { key: "phone", label: "Phone" },
                { key: "branch", label: "Branch" },
                { key: "therapist", label: "Therapist" },
                { key: "visits", label: "Visits" },
                { key: "sessions", label: "Sessions" },
                { key: "outstandingAmount", label: "Outstanding" },
                { key: "status", label: "Status" },
              ]}
              rows={exportRows}
              logoUri={logoUri}
              meta={[
                { label: "Total Patients", value: String(rows.length) },
                { label: "Generated By", value: user?.name ?? "" },
                { label: "Generated", value: new Date().toLocaleString() },
              ]}
            />
            <Button
              variant="outline"
              onClick={handleBulkDownload}
              disabled={bulkDownloading}
            >
              {bulkDownloading ? (
                <Loader2 className="h-4 w-4 mr-2 animate-spin" />
              ) : (
                <Download className="h-4 w-4 mr-2" />
              )}
              Download ID Cards (ZIP)
            </Button>
          </div>
        ) : null
      }
    >
      {bulkDownloading && (
        <div className="rounded-lg border bg-card p-3">
          <div className="flex items-center justify-between text-sm font-medium text-foreground">
            <span>Generating {bulkTotal} ID cards…</span>
            <Loader2 className="h-4 w-4 animate-spin text-primary" />
          </div>
          <Progress className="mt-2" value={undefined} />
          <div className="mt-2 text-xs text-muted-foreground">
            Building a ZIP on the server — keep this tab open until the download starts.
          </div>
        </div>
      )}
      <ReportDataTable
        columns={[
          { key: "patientCode", label: "ID", render: (r) => String(r.patientCode || r.patientId) },
          { key: "patientName", label: "Name" },
          { key: "phone", label: "Phone" },
          { key: "branch", label: "Branch" },
          { key: "therapist", label: "Therapist" },
          { key: "visits", label: "Visits" },
          { key: "sessions", label: "Sessions" },
          { key: "outstandingAmount", label: "Outstanding", render: (r) => formatLkr(Number(r.outstandingAmount)) },
          { key: "status", label: "Status" },
        ]}
        rows={rows}
        searchKeys={["patientName", "phone", "patientCode", "therapist"]}
      />
    </ReportPageShell>
  );
}

export default function PatientExportPage() {
  return (
    <RoleProtectedRoute allowed={canExportPatients}>
      <PatientExportContent />
    </RoleProtectedRoute>
  );
}
